server:
  port: 80

spring:
  application:
    name: cloud-consumer-service
  zipkin:
    base-url: http://121.43.169.252:9411
    sleuth:
      sampler:
        probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.169.252:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root1
    password: root

eureka:
  client:
    register-with-eureka: true  #表示不向注册中心注册自己
    fetch-registry: true  #是否从eurekaServer抓取已有的注册信息，默认是true 单点无所谓 集群必须设置为true  配合ribbin使用实现负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sxl.springcloud.entities