server:
  port: 80

spring:
  application:
    name: cloud-consumer-service-feign


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
logging:
  level:
    com.sxl.springcloud.service.PaymentFeignService: debug

